### ISSUE TITLE
Upload 1.2 to the PyPI

### ISSUE THREAD

**Issue by cmr** [MHordecki/easyply#3]

**Comment by MHordecki** [comment]
Done!

**Comment by cmr** [comment]
Thanks, that was quick!

On Tue, Feb 2, 2016, at 20:20, Mike Hordecki wrote:
> Done!
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/MHordecki/easyply/issues/3#issuecomment-178940422


-- 
/cmr
